zuul:
  routes:
    ui:
      url: http://localhost:8081
    admin:
      url: http://localhost:8082
    resource:
      url: http://localhost:9000
security:
  user:
    password:
      password
  sessions: ALWAYS
spring:
  redis:
    host: 192.168.99.100